### ISSUE TITLE
Running folium with klokantech/tileserver-gl

### ISSUE THREAD

**Issue by psychemedia** [python-visualization/folium#637]
Does anyone have examples of using `folium` to display maps using tiles server by the [`klokantech/tileserver-gl`](https://github.com/klokantech/tileserver-gl) `docker` container?

eg I am using Jupyter notebook and tileserver linked containers, as well as a UK postcode geocoding server, using the following `docker-compose` script:

````
tileserver:
  image: klokantech/tileserver-gl
  ports:
    - 8080:80
  volumes:
    - .:/data
 
postcodes: 
 image: randomvariable/docker-postcodes.io
 ports:
    - 8000:8000 
    
jupyterscipy:
  image: psychemedia/ou-tm351-jupyter-custom-pystack-test
  ports:
    - 8899:8888
  links:
    - tileserver:tileserver
    - postcodes:postcodes 
  volumes:
    - .:/home/jovyan/work
````

FWIW, the postcodes connection is via:

````
import requests, json
postcode = 'MK7 6AA'
r=requests.get('http://postcodes:8000/postcodes/{PC}'.format(PC=postcode))
r.json()
````

But how do I get `folium` to use the `klokantech/tileserver-g` served tiles? The service itself suggests a URL format of `http://tileserver:8081/data/v3/{z}/{x}/{y}.pbf`.
